[package]
name = "pylitesvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pylitesvm"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.21"
pyo3 = "0.19.0"
pyo3-log = "0.9.0"
